name: $(BuildID)

variables:
  RGName: RG-Functions
  FunctionAppName: svhbh54pwshfunctions
  VSTS_AGENT_INPUT_URL: "https://dev.azure.com/stijnverhoeven-realdolmen"
  VSTS_AGENT_INPUT_AUTH: "pat"
  VSTS_AGENT_INPUT_TOKEN: "@Microsoft.KeyVault(SecretUri=https://svhbh54keyvault.vault.azure.net/secrets/AzureDevopsPAT/0f38f3e90fd94d498f44135e6b1d3eaf)"
  VSTS_AGENT_INPUT_AGENT: "linuxagent"
  VSTS_AGENT_INPUT_POOL: "ACIPool"
  IMAGENAME: "sverhoacrrd.azurecr.io/azuredevopslinuxagent:1989"
  ACRUSERNAME: "sverhoacrrd"
  ACRPASSWORD: "@Microsoft.KeyVault(SecretUri=https://svhbh54keyvault.vault.azure.net/secrets/ACRPassword/722b5b4b41af4dbfb28b728fd8a85a78)"

trigger:
  branches:
    include:
    - master

  paths:
    include:
    - AzureFunction/*
    exclude:
    - README.md

stages:
  - stage: 'validate_stage_template'
    displayName: 'Validate Function App template'
    jobs:
      - job: 'deploy_fa'
        displayName: 'Release Powershell Functions'
        continueOnError: false
        pool:
          queue: 'ubuntu'
        workspace:
          clean: all
        steps:
        - task: ArchiveFiles@2
          displayName: 'Archiving DeployACIContainer Function'
          inputs:
            rootFolderOrFile: AzureFunction/
            includeRootFolder: false
            replaceExistingArchive: true
            archiveFile: $(System.DefaultWorkingDirectory)/functions.zip
        - task: AzureFunctionApp@1
          displayName: Azure Function App Deploy
          inputs:
            azureSubscription: svhbh54-msdn
            appName: $(FunctionAppName)
            package: $(System.DefaultWorkingDirectory)/functions.zip
            appSettings: |
              -VSTS_AGENT_INPUT_URL $(VSTS_AGENT_INPUT_URL)