name: $(BuildID)

variables:
  acrname: sverhoacrrd
  rgName: RG-ACI

trigger: none

stages:
- stage: 'deploy_acicontainergroup'
  displayName: 'Deploy ACI Container Group for Azure DevOps Agent'
  variables:
    - group: 'ACI-AzureDevOpsAgent'
  jobs:
  - job: 'deploy_aci_azuredevopsagent'
    displayName: 'Deploy ACI Container Group'
    continueOnError: false
    pool:
      vmImage: 'ubuntu-latest'
    workspace:
      clean: all
    steps:
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'svhbh54-msdn'
        KeyVaultName: 'svhbh54keyvault'
        SecretsFilter: AzureDevopsPAT
    - task: replacetokens@3
      inputs:
        rootDirectory: 'ACIYaml'
        targetFiles: '*.yml'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        useLegacyPattern: false
        enableTelemetry: true
    - task: AzureCLI@1
      inputs:
        azureSubscription: svhbh54-msdn
        scriptLocation: inlineScript
        inlineScript: |
          az container create -g $(rgName) -f ACIYaml/deploy-agent.yml
        
        